/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardScrapingNewsRouteImport } from './routes/dashboard.scraping-news'
import { Route as DashboardConversationRouteImport } from './routes/dashboard.conversation'
import { Route as DashboardBroadcastRouteImport } from './routes/dashboard.broadcast'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAiAgentRouteImport } from './routes/dashboard.ai-agent'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScrapingNewsRoute = DashboardScrapingNewsRouteImport.update({
  id: '/scraping-news',
  path: '/scraping-news',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationRoute = DashboardConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBroadcastRoute = DashboardBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAgentRoute = DashboardAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/broadcast': typeof DashboardBroadcastRoute
  '/dashboard/conversation': typeof DashboardConversationRoute
  '/dashboard/scraping-news': typeof DashboardScrapingNewsRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/broadcast': typeof DashboardBroadcastRoute
  '/dashboard/conversation': typeof DashboardConversationRoute
  '/dashboard/scraping-news': typeof DashboardScrapingNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/broadcast': typeof DashboardBroadcastRoute
  '/dashboard/conversation': typeof DashboardConversationRoute
  '/dashboard/scraping-news': typeof DashboardScrapingNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/dashboard/ai-agent'
    | '/dashboard/analytics'
    | '/dashboard/broadcast'
    | '/dashboard/conversation'
    | '/dashboard/scraping-news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/dashboard/ai-agent'
    | '/dashboard/analytics'
    | '/dashboard/broadcast'
    | '/dashboard/conversation'
    | '/dashboard/scraping-news'
  id:
    | '__root__'
    | '/dashboard'
    | '/login'
    | '/dashboard/ai-agent'
    | '/dashboard/analytics'
    | '/dashboard/broadcast'
    | '/dashboard/conversation'
    | '/dashboard/scraping-news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scraping-news': {
      id: '/dashboard/scraping-news'
      path: '/scraping-news'
      fullPath: '/dashboard/scraping-news'
      preLoaderRoute: typeof DashboardScrapingNewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversation': {
      id: '/dashboard/conversation'
      path: '/conversation'
      fullPath: '/dashboard/conversation'
      preLoaderRoute: typeof DashboardConversationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/broadcast': {
      id: '/dashboard/broadcast'
      path: '/broadcast'
      fullPath: '/dashboard/broadcast'
      preLoaderRoute: typeof DashboardBroadcastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-agent': {
      id: '/dashboard/ai-agent'
      path: '/ai-agent'
      fullPath: '/dashboard/ai-agent'
      preLoaderRoute: typeof DashboardAiAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiAgentRoute: typeof DashboardAiAgentRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBroadcastRoute: typeof DashboardBroadcastRoute
  DashboardConversationRoute: typeof DashboardConversationRoute
  DashboardScrapingNewsRoute: typeof DashboardScrapingNewsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiAgentRoute: DashboardAiAgentRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBroadcastRoute: DashboardBroadcastRoute,
  DashboardConversationRoute: DashboardConversationRoute,
  DashboardScrapingNewsRoute: DashboardScrapingNewsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
